### ISSUE TITLE
Can we get 0.0.10 on maven central?

### ISSUE THREAD

**Issue by ankit--sethi** [opentracing-contrib/java-ejb#10]
Hi, I'm looking to use this version and the latest on Maven Central is 0.0.8

**Comment by jpkrohling** [comment]
Sorry, I had some troubles with Maven Central and bintray, and decided to just publish in this project's GitHub Maven Repo.

https://github.com/opentracing-contrib/java-ejb/packages/804060

See this also: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#publishing-a-package
