### ISSUE TITLE
Move to java-interceptor

### ISSUE THREAD

**Issue by jpkrohling** [opentracing-contrib/java-ejb#4]
This module would be more appropriately named `java-interceptor` instead of `java-ejb`. Once this is done, the `java-cdi` module could depend on this new module.

**Comment by pavolloffay** [comment]
I think `java-interceptor` is too generic name.

**Comment by jpkrohling** [comment]
`java-javax-interceptor`? It's about `javax.interceptor.*`, so, not sure there's a more appropriate name :/

**Comment by hypnoce** [comment]
Hi all,

maybe `java-cdi-interceptor` ? I'm a bad namer maybe :)

Thanks !
